#!/bin/sh
# Stats the .env file in the parent dir
SQLFILES=(
"00_rename.sql"
#"01_debate.sql"
"03_misspelled.sql"
#"04_vocab.sql"
"05_top_speakers.sql"
"06_frequencyCounts.sql"
"99_indexes.sql"
)
LOGFILE="rebuildAPI.log"
echo "Rebuilding, logging to: $LOGFILE..."

exec 3>&1 4>&2
trap 'exec 2>&4 1>&3' 0 1 2 3
exec 1>$LOGFILE 2>&1

set -o allexport
[[ -f ../../.env ]] && source ../../.env
set +o allexport
export PGPASSWORD=$DATABASE_PASS
for i in "${SQLFILES[@]}"
do
   :
   echo "\n$i -------------------------------------------------------------------------------------------"
   psql -h $DATABASE_SERVER -p $DATABASE_PORT -d $DATABASE_DB -U $DATABASE_USERNAME < ../api/$i
done
