#!/bin/sh
# Stats the .env file in the parent dir
set -o allexport
[[ -f ../../.env ]] && source ../../.env
set +o allexport
echo "Importing: $1"
export PGPASSWORD=$DATABASE_PASS

psql -h $DATABASE_SERVER -p $DATABASE_PORT -d $DATABASE_DB -U $DATABASE_USERNAME -c 'SHOW config_file'
psql -h $DATABASE_SERVER -p $DATABASE_PORT -d $DATABASE_DB -U $DATABASE_USERNAME -c 'SHOW hba_file';
